# Generated by Django 6.0.6 on 2026-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentid_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.CharField(max_length=30),
        ),
    ]
