# Generated by Django 6.0.6 on 2026-07-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmarks',
            options={'ordering': ['student']},
        ),
    ]
