# Generated by Django 6.0.6 on 2026-07-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_subjectmarks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmarks', to='home.student'),
        ),
    ]
